/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OfferStatus = IDL.Variant({
  'Countered' : IDL.Null,
  'Rejected' : IDL.Null,
  'Accepted' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const OfferToken = IDL.Variant({
  'ICP' : IDL.Null,
  'ckBTC' : IDL.Null,
  'ckETH' : IDL.Null,
  'ckUSDC' : IDL.Null,
  'ckUSDT' : IDL.Null,
});
export const OfferAction = IDL.Variant({
  'Countered' : IDL.Null,
  'Rejected' : IDL.Null,
  'Accepted' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Submitted' : IDL.Null,
});
export const OfferHistoryEntry = IDL.Record({
  'by' : IDL.Principal,
  'token' : OfferToken,
  'action' : OfferAction,
  'timestamp' : Timestamp,
  'amount' : IDL.Nat,
});
export const Offer = IDL.Record({
  'id' : IDL.Text,
  'nft_id' : IDL.Text,
  'status' : OfferStatus,
  'updated_at' : Timestamp,
  'history' : IDL.Vec(OfferHistoryEntry),
  'created_at' : Timestamp,
  'seller' : IDL.Principal,
  'offered_token' : OfferToken,
  'offered_amount' : IDL.Nat,
  'buyer' : IDL.Principal,
  'icp_equivalent' : IDL.Nat,
});
export const ArtworkLayerId = IDL.Nat;
export const ArtworkLayer = IDL.Record({
  'id' : ArtworkLayerId,
  'layer_number' : IDL.Nat,
  'name' : IDL.Text,
  'object_key' : IDL.Text,
  'uploaded_at' : Timestamp,
});
export const PlantId = IDL.Nat;
export const AddFeedingInput = IDL.Record({
  'dosage_amount' : IDL.Text,
  'date' : Timestamp,
  'nutrient_type' : IDL.Text,
  'product_name' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'plant_id' : PlantId,
});
export const FeedingId = IDL.Nat;
export const FeedingPublic = IDL.Record({
  'id' : FeedingId,
  'dosage_amount' : IDL.Text,
  'date' : Timestamp,
  'nutrient_type' : IDL.Text,
  'product_name' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'plant_id' : PlantId,
});
export const AddWeatherRecordInput = IDL.Record({
  'latitude' : IDL.Float64,
  'temperature_max' : IDL.Float64,
  'temperature_min' : IDL.Float64,
  'precipitation' : IDL.Float64,
  'wind_speed' : IDL.Opt(IDL.Float64),
  'date' : IDL.Text,
  'humidity' : IDL.Opt(IDL.Float64),
  'longitude' : IDL.Float64,
});
export const WeatherRecordId = IDL.Nat;
export const WeatherRecord = IDL.Record({
  'id' : WeatherRecordId,
  'latitude' : IDL.Float64,
  'temperature_max' : IDL.Float64,
  'temperature_min' : IDL.Float64,
  'precipitation' : IDL.Float64,
  'wind_speed' : IDL.Opt(IDL.Float64),
  'date' : IDL.Text,
  'user' : IDL.Principal,
  'humidity' : IDL.Opt(IDL.Float64),
  'recorded_at' : Timestamp,
  'longitude' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AssignAction = IDL.Variant({
  'AssignToQR' : IDL.Record({ 'claim_token' : IDL.Text }),
  'ListOnShop' : IDL.Record({ 'product_id' : IDL.Nat }),
  'Airdrop' : IDL.Record({ 'to' : IDL.Principal }),
});
export const AirdropAssignment = IDL.Record({
  'recipient' : IDL.Principal,
  'nftId' : IDL.Nat,
});
export const QRAssignmentResult = IDL.Record({
  'claimTokenId' : IDL.Text,
  'nftId' : IDL.Nat,
});
export const ShopAssignment = IDL.Record({
  'nftId' : IDL.Nat,
  'price' : IDL.Nat,
});
export const RarityTier = IDL.Variant({
  'Rare' : IDL.Null,
  'Uncommon' : IDL.Null,
  'Common' : IDL.Null,
});
export const NFTStandard = IDL.Variant({
  'EXT' : IDL.Null,
  'Hedera' : IDL.Null,
  'ICRC37' : IDL.Null,
});
export const FoundersMintInput = IDL.Record({
  'layerCombination' : IDL.Vec(IDL.Nat),
  'recipient' : IDL.Principal,
  'rarityTier' : RarityTier,
  'badgeImageKey' : IDL.Text,
  'nft_standard' : NFTStandard,
  'compositeImageKey' : IDL.Text,
});
export const FoundersMintResult = IDL.Record({
  'tokenId' : IDL.Text,
  'recipient' : IDL.Principal,
  'standard' : NFTStandard,
});
export const InventoryCategory = IDL.Variant({
  'OtherSize' : IDL.Text,
  'Gal1' : IDL.Null,
  'Gal3' : IDL.Null,
  'Gal5' : IDL.Null,
  'Oz16' : IDL.Null,
  'InGround' : IDL.Null,
});
export const ProductCategory = IDL.Variant({
  'Spice' : IDL.Null,
  'Seedling' : IDL.Null,
  'GardenInputs' : IDL.Null,
  'Gallon1' : IDL.Null,
  'Gallon5' : IDL.Null,
});
export const CreateProductInput = IDL.Record({
  'image_key' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'price_cents' : IDL.Nat,
  'description' : IDL.Text,
  'inventory_category' : IDL.Opt(InventoryCategory),
  'image_keys' : IDL.Vec(IDL.Text),
  'category' : ProductCategory,
  'variety' : IDL.Opt(IDL.Text),
  'plant_id' : IDL.Opt(PlantId),
});
export const ProductId = IDL.Nat;
export const ProductPublic = IDL.Record({
  'id' : ProductId,
  'active' : IDL.Bool,
  'image_key' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'price_cents' : IDL.Nat,
  'description' : IDL.Text,
  'inventory_category' : IDL.Opt(InventoryCategory),
  'image_keys' : IDL.Vec(IDL.Text),
  'category' : ProductCategory,
  'variety' : IDL.Opt(IDL.Text),
  'plant_id' : IDL.Opt(PlantId),
});
export const BulkCreateResult = IDL.Variant({
  'ok' : ProductPublic,
  'err' : IDL.Text,
});
export const CounterOfferInput = IDL.Record({
  'counter_amount' : IDL.Nat,
  'offer_id' : IDL.Text,
  'counter_token' : OfferToken,
});
export const ClaimTokenId = IDL.Text;
export const BatchGiftPackPublic = IDL.Record({
  'id' : IDL.Text,
  'creator' : IDL.Principal,
  'plant_ids' : IDL.Vec(PlantId),
  'redeemed' : IDL.Bool,
  'created_at' : Timestamp,
  'redeemed_by' : IDL.Opt(IDL.Principal),
  'claim_token_id' : ClaimTokenId,
  'highest_rarity_pct' : IDL.Nat,
});
export const PostId = IDL.Nat;
export const CreateCommentInput = IDL.Record({
  'post_id' : PostId,
  'content' : IDL.Text,
});
export const CommentId = IDL.Nat;
export const CommentPublic = IDL.Record({
  'id' : CommentId,
  'post_id' : PostId,
  'content' : IDL.Text,
  'created_at' : Timestamp,
  'author' : IDL.Principal,
  'author_username' : IDL.Opt(IDL.Text),
});
export const ProposalType = IDL.Variant({
  'General' : IDL.Null,
  'Seasoning' : IDL.Null,
  'PlantVariety' : IDL.Null,
});
export const CreateProposalInput = IDL.Record({
  'title' : IDL.Text,
  'ends_at' : Timestamp,
  'description' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
  'proposal_type' : ProposalType,
});
export const ProposalId = IDL.Nat;
export const ProposalPublic = IDL.Record({
  'id' : ProposalId,
  'title' : IDL.Text,
  'vote_counts' : IDL.Vec(IDL.Nat),
  'ends_at' : Timestamp,
  'description' : IDL.Text,
  'created_at' : Timestamp,
  'created_by' : IDL.Principal,
  'voter_count' : IDL.Nat,
  'caller_vote' : IDL.Opt(IDL.Nat),
  'options' : IDL.Vec(IDL.Text),
  'proposal_type' : ProposalType,
});
export const OrderItem = IDL.Record({
  'product_id' : ProductId,
  'price_cents' : IDL.Nat,
  'quantity' : IDL.Nat,
  'plant_id' : IDL.Opt(PlantId),
});
export const CreateOrderInput = IDL.Record({
  'shipping_address' : IDL.Opt(IDL.Text),
  'pickup' : IDL.Bool,
  'items' : IDL.Vec(OrderItem),
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'PickedUp' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Shipped' : IDL.Null,
  'Pending' : IDL.Null,
});
export const OrderPublic = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'shipping_address' : IDL.Opt(IDL.Text),
  'created_at' : Timestamp,
  'pickup' : IDL.Bool,
  'buyer' : IDL.Principal,
  'items' : IDL.Vec(OrderItem),
  'total_cents' : IDL.Nat,
});
export const ContainerSize = IDL.Variant({
  'Gal5Bucket' : IDL.Null,
  'Gal1' : IDL.Null,
  'Gal3' : IDL.Null,
  'Gal5' : IDL.Null,
  'Oz16' : IDL.Null,
  'Gal7GrowBag' : IDL.Null,
  'Cell72' : IDL.Null,
  'Pot4Inch' : IDL.Null,
  'InGround' : IDL.Null,
  'Pot6Inch' : IDL.Null,
  'Gal10GrowBag' : IDL.Null,
  'Gal1New' : IDL.Null,
  'Gal3New' : IDL.Null,
  'Gal7Pot' : IDL.Null,
  'Cell128' : IDL.Null,
  'Gal15GrowBag' : IDL.Null,
  'Gal5GrowBag' : IDL.Null,
  'Other' : IDL.Text,
});
export const TrayId = IDL.Nat;
export const CreatePlantInput = IDL.Record({
  'container_size' : IDL.Opt(ContainerSize),
  'date_purchased' : IDL.Opt(Timestamp),
  'origin' : IDL.Opt(IDL.Text),
  'common_name' : IDL.Opt(IDL.Text),
  'source_plant_id' : IDL.Opt(PlantId),
  'cell_position' : IDL.Nat,
  'watering_schedule' : IDL.Opt(IDL.Text),
  'pest_notes' : IDL.Opt(IDL.Text),
  'tray_id' : TrayId,
  'notes' : IDL.Text,
  'planting_date' : Timestamp,
  'additional_notes' : IDL.Opt(IDL.Text),
  'genetics' : IDL.Text,
  'variety' : IDL.Text,
  'nft_standard' : NFTStandard,
  'latin_name' : IDL.Opt(IDL.Text),
});
export const PlantStage = IDL.Variant({
  'Seedling' : IDL.Null,
  'Seed' : IDL.Null,
  'Mature' : IDL.Null,
});
export const PlantPublic = IDL.Record({
  'id' : PlantId,
  'nft_id' : IDL.Opt(IDL.Text),
  'container_size' : IDL.Opt(ContainerSize),
  'origin' : IDL.Opt(IDL.Text),
  'sold' : IDL.Bool,
  'is_transplanted' : IDL.Bool,
  'common_name' : IDL.Opt(IDL.Text),
  'for_sale' : IDL.Bool,
  'created_by' : IDL.Principal,
  'is_cooked' : IDL.Bool,
  'source_plant_id' : IDL.Opt(PlantId),
  'cell_position' : IDL.Nat,
  'watering_schedule' : IDL.Opt(IDL.Text),
  'pest_notes' : IDL.Opt(IDL.Text),
  'sold_to' : IDL.Opt(IDL.Principal),
  'stage' : PlantStage,
  'germination_date' : IDL.Opt(Timestamp),
  'tray_id' : TrayId,
  'notes' : IDL.Text,
  'planting_date' : Timestamp,
  'transplant_date' : IDL.Opt(Timestamp),
  'additional_notes' : IDL.Opt(IDL.Text),
  'photo_keys' : IDL.Vec(IDL.Text),
  'genetics' : IDL.Text,
  'variety' : IDL.Text,
  'transplant_plant_id' : IDL.Opt(PlantId),
  'nft_standard' : NFTStandard,
  'photos' : IDL.Vec(IDL.Text),
  'latin_name' : IDL.Opt(IDL.Text),
});
export const CreatePostInput = IDL.Record({
  'content' : IDL.Text,
  'image_key' : IDL.Opt(IDL.Text),
  'anonymous' : IDL.Bool,
});
export const PostPublic = IDL.Record({
  'id' : PostId,
  'updated_at' : Timestamp,
  'content' : IDL.Text,
  'author_text' : IDL.Text,
  'comment_count' : IDL.Nat,
  'image_key' : IDL.Opt(IDL.Text),
  'like_count' : IDL.Nat,
  'created_at' : Timestamp,
  'author_principal' : IDL.Opt(IDL.Principal),
  'author_username' : IDL.Opt(IDL.Text),
  'is_anonymous' : IDL.Bool,
  'caller_liked' : IDL.Bool,
});
export const CreateRecipeInput = IDL.Record({
  'photo_key' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'instructions' : IDL.Vec(IDL.Text),
  'is_featured' : IDL.Bool,
  'shop_link' : IDL.Opt(IDL.Text),
  'shop_link_label' : IDL.Opt(IDL.Text),
  'application_notes' : IDL.Text,
  'full_name' : IDL.Text,
  'ingredients' : IDL.Vec(IDL.Text),
});
export const RecipeId = IDL.Nat;
export const Recipe = IDL.Record({
  'id' : RecipeId,
  'updated_at' : Timestamp,
  'photo_key' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'created_at' : Timestamp,
  'instructions' : IDL.Vec(IDL.Text),
  'is_featured' : IDL.Bool,
  'shop_link' : IDL.Opt(IDL.Text),
  'shop_link_label' : IDL.Opt(IDL.Text),
  'application_notes' : IDL.Text,
  'full_name' : IDL.Text,
  'ingredients' : IDL.Vec(IDL.Text),
});
export const CreateTrayInput = IDL.Record({
  'name' : IDL.Text,
  'planting_date' : Timestamp,
  'nft_standard' : NFTStandard,
});
export const TrayPublic = IDL.Record({
  'id' : TrayId,
  'cells' : IDL.Vec(IDL.Opt(PlantId)),
  'name' : IDL.Text,
  'cell_count' : IDL.Nat,
  'planting_date' : Timestamp,
  'nft_standard' : NFTStandard,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const LayerSummary = IDL.Record({
  'file_names' : IDL.Vec(IDL.Text),
  'layer' : IDL.Text,
  'file_count' : IDL.Nat,
});
export const UploadResult = IDL.Record({
  'layers_detected' : IDL.Nat,
  'asset_canister_id' : IDL.Text,
  'total_files' : IDL.Nat,
  'layer_summaries' : IDL.Vec(LayerSummary),
});
export const ClaimTokenPublic = IDL.Record({
  'id' : ClaimTokenId,
  'created_at' : Timestamp,
  'redeemed_at' : IDL.Opt(Timestamp),
  'redeemed_by' : IDL.Opt(IDL.Principal),
  'claim_data' : IDL.Text,
  'rarity_tier' : RarityTier,
  'plant_id' : PlantId,
});
export const ResaleListingPublic = IDL.Record({
  'id' : IDL.Text,
  'seller' : IDL.Principal,
  'is_active' : IDL.Bool,
  'price_icp' : IDL.Float64,
  'rarity_tier' : RarityTier,
  'listed_at' : Timestamp,
  'plant_id' : PlantId,
});
export const UploadSessionStatus = IDL.Record({
  'total_chunks' : IDL.Nat,
  'received' : IDL.Nat,
  'started_at' : Timestamp,
});
export const MembershipTier = IDL.Variant({
  'Premium' : IDL.Null,
  'Standard' : IDL.Null,
});
export const MembershipNFTPublic = IDL.Record({
  'id' : IDL.Nat,
  'nft_id' : IDL.Opt(IDL.Text),
  'issued_at' : Timestamp,
  'owner' : IDL.Principal,
  'tier' : MembershipTier,
  'is_founder' : IDL.Bool,
  'layer_combination' : IDL.Vec(IDL.Nat),
  'rarity_tier' : IDL.Opt(RarityTier),
  'nft_standard' : IDL.Variant({
    'EXT' : IDL.Null,
    'Hedera' : IDL.Null,
    'ICRC37' : IDL.Null,
  }),
});
export const UserProfilePublic = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'avatar_key' : IDL.Opt(IDL.Text),
  'following_count' : IDL.Nat,
  'created_at' : Timestamp,
  'follower_count' : IDL.Nat,
  'principal_id' : IDL.Principal,
});
export const OracleToken = IDL.Variant({
  'ICP' : IDL.Null,
  'ckBTC' : IDL.Null,
  'ckETH' : IDL.Null,
  'ckUSDC' : IDL.Null,
  'ckUSDT' : IDL.Null,
});
export const ScheduleId = IDL.Text;
export const SavedSchedule = IDL.Record({
  'id' : ScheduleId,
  'owner' : IDL.Principal,
  'created_at' : Timestamp,
  'stage' : IDL.Text,
  'inputs' : IDL.Vec(IDL.Text),
  'share_token' : IDL.Text,
});
export const StageHistory = IDL.Record({
  'stage' : PlantStage,
  'notes' : IDL.Text,
  'timestamp' : Timestamp,
});
export const PlantTimeline = IDL.Record({
  'stage_history' : IDL.Vec(StageHistory),
  'feedings' : IDL.Vec(FeedingPublic),
  'plant' : PlantPublic,
});
export const PoolDashboard = IDL.Record({
  'total' : IDL.Nat,
  'listed_on_shop' : IDL.Nat,
  'assigned_to_qr' : IDL.Nat,
  'airdropped' : IDL.Nat,
  'ready' : IDL.Nat,
});
export const PoolNFTStatus = IDL.Variant({
  'ListedOnShop' : IDL.Record({ 'at' : Timestamp, 'product_id' : IDL.Nat }),
  'Ready' : IDL.Null,
  'AssignedToQR' : IDL.Record({ 'at' : Timestamp, 'claim_token' : IDL.Text }),
  'Airdropped' : IDL.Record({ 'at' : Timestamp, 'to' : IDL.Principal }),
});
export const PoolNFTRarity = IDL.Variant({
  'Rare' : IDL.Null,
  'Uncommon' : IDL.Null,
  'Common' : IDL.Null,
});
export const PoolNFTPublic = IDL.Record({
  'id' : IDL.Nat,
  'status' : PoolNFTStatus,
  'generated_at' : Timestamp,
  'token_id' : IDL.Text,
  'image_key' : IDL.Text,
  'layer_combo' : IDL.Vec(IDL.Text),
  'rarity' : PoolNFTRarity,
});
export const PoolNFTStatus__1 = IDL.Variant({
  'Shop' : IDL.Null,
  'QRAssigned' : IDL.Null,
  'Ready' : IDL.Null,
  'Airdropped' : IDL.Null,
});
export const PoolNFTPublic__1 = IDL.Record({
  'id' : IDL.Nat,
  'status' : PoolNFTStatus__1,
  'shopProductId' : IDL.Opt(IDL.Nat),
  'assignedAt' : IDL.Opt(Timestamp),
  'assignedTo' : IDL.Opt(IDL.Principal),
  'layerCombination' : IDL.Vec(IDL.Nat),
  'rarityTier' : RarityTier,
  'claimTokenId' : IDL.Opt(IDL.Text),
  'compositeImageKey' : IDL.Text,
});
export const PoolStats = IDL.Record({
  'shop' : IDL.Nat,
  'totalByRarity' : IDL.Record({
    'rare' : IDL.Nat,
    'common' : IDL.Nat,
    'uncommon' : IDL.Nat,
  }),
  'qrAssigned' : IDL.Nat,
  'airdropped' : IDL.Nat,
  'ready' : IDL.Nat,
});
export const ScheduleEntry = IDL.Record({
  'timing' : IDL.Text,
  'dilution' : IDL.Text,
  'stage' : IDL.Text,
  'notes' : IDL.Text,
  'frequency' : IDL.Text,
  'input_name' : IDL.Text,
});
export const TokenPrice = IDL.Record({
  'token' : OracleToken,
  'price_in_icp_e8s' : IDL.Nat,
  'last_updated' : Timestamp,
});
export const TreasuryToken = IDL.Variant({
  'ICP' : IDL.Null,
  'ckBTC' : IDL.Null,
  'ckETH' : IDL.Null,
  'ckUSDC' : IDL.Null,
  'ckUSDT' : IDL.Null,
});
export const TreasuryBalance = IDL.Record({
  'token' : TreasuryToken,
  'balance_e8s' : IDL.Nat,
});
export const TreasuryTxType = IDL.Variant({
  'Deposit' : IDL.Null,
  'Withdrawal' : IDL.Null,
  'OfferSettlement' : IDL.Null,
  'Transfer' : IDL.Null,
});
export const TreasuryTransaction = IDL.Record({
  'id' : IDL.Text,
  'token' : TreasuryToken,
  'to_principal' : IDL.Opt(IDL.Principal),
  'memo' : IDL.Opt(IDL.Text),
  'from_principal' : IDL.Opt(IDL.Principal),
  'amount_e8s' : IDL.Nat,
  'offer_id' : IDL.Opt(IDL.Text),
  'timestamp' : Timestamp,
  'tx_type' : TreasuryTxType,
});
export const LifecycleUpgradeEvent = IDL.Record({
  'new_stage' : IDL.Text,
  'old_nft_id' : IDL.Opt(IDL.Text),
  'old_stage' : IDL.Text,
  'upgraded_at' : Timestamp,
  'new_nft_id' : IDL.Text,
  'plant_id' : PlantId,
});
export const WalletToken = IDL.Record({
  'decimals' : IDL.Nat8,
  'balance' : IDL.Nat,
  'name' : IDL.Text,
  'usdValue' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const TxStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const TxType = IDL.Variant({ 'receive' : IDL.Null, 'send' : IDL.Null });
export const WalletTransaction = IDL.Record({
  'id' : IDL.Text,
  'status' : TxStatus,
  'counterparty' : IDL.Text,
  'tokenSymbol' : IDL.Text,
  'timestamp' : Timestamp,
  'txType' : TxType,
  'amount' : IDL.Nat,
});
export const MintRWAProvenanceInput = IDL.Record({
  'custom_notes' : IDL.Text,
  'artwork_layer_id' : ArtworkLayerId,
  'rarity_tier' : IDL.Nat,
  'plant_id' : PlantId,
});
export const SaveProfileInput = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'avatar_key' : IDL.Opt(IDL.Text),
});
export const SendTokenInput = IDL.Record({
  'tokenSymbol' : IDL.Text,
  'recipientAddress' : IDL.Text,
  'amount' : IDL.Nat,
});
export const StoredFile = IDL.Record({
  'data' : IDL.Vec(IDL.Nat8),
  'path' : IDL.Text,
  'size' : IDL.Nat,
  'mime_type' : IDL.Text,
  'layer' : IDL.Text,
  'filename' : IDL.Text,
  'uploaded_at' : Timestamp,
});
export const SubmitOfferInput = IDL.Record({
  'nft_id' : IDL.Text,
  'offered_token' : OfferToken,
  'offered_amount' : IDL.Nat,
});
export const TransplantInput = IDL.Record({
  'container_size' : ContainerSize,
  'plant_id' : PlantId,
});
export const UpdateCellDataInput = IDL.Record({
  'origin' : IDL.Opt(IDL.Text),
  'common_name' : IDL.Opt(IDL.Text),
  'watering_schedule' : IDL.Opt(IDL.Text),
  'pest_notes' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'additional_notes' : IDL.Opt(IDL.Text),
  'plant_id' : PlantId,
  'latin_name' : IDL.Opt(IDL.Text),
});
export const UpdatePlantMetadataInput = IDL.Record({
  'notes' : IDL.Opt(IDL.Text),
  'genetics' : IDL.Opt(IDL.Text),
  'photos' : IDL.Opt(IDL.Vec(IDL.Text)),
  'plant_id' : PlantId,
});
export const UpdateProductInput = IDL.Record({
  'active' : IDL.Opt(IDL.Bool),
  'product_id' : ProductId,
  'image_key' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'price_cents' : IDL.Opt(IDL.Nat),
  'description' : IDL.Opt(IDL.Text),
  'image_keys' : IDL.Opt(IDL.Vec(IDL.Text)),
});
export const UpdateRecipeInput = IDL.Record({
  'id' : RecipeId,
  'photo_key' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
  'description' : IDL.Opt(IDL.Text),
  'instructions' : IDL.Opt(IDL.Vec(IDL.Text)),
  'is_featured' : IDL.Opt(IDL.Bool),
  'shop_link' : IDL.Opt(IDL.Text),
  'shop_link_label' : IDL.Opt(IDL.Text),
  'application_notes' : IDL.Opt(IDL.Text),
  'full_name' : IDL.Opt(IDL.Text),
  'ingredients' : IDL.Opt(IDL.Vec(IDL.Text)),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Nat8)],
      [],
    ),
  '_immutableObjectStorageGetCertificate' : IDL.Func(
      [],
      [IDL.Opt(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'acceptOffer' : IDL.Func([IDL.Text], [Offer], []),
  'addArtworkLayer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [ArtworkLayer],
      [],
    ),
  'addFeedingRecord' : IDL.Func([AddFeedingInput], [FeedingPublic], []),
  'addPlantPhoto' : IDL.Func([PlantId, IDL.Text], [], []),
  'addWeatherRecord' : IDL.Func([AddWeatherRecordInput], [WeatherRecord], []),
  'adminSubmitToDAB' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'airdropNFT' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignPoolNFT' : IDL.Func([IDL.Nat, AssignAction], [], []),
  'batchAirdropFromPool' : IDL.Func(
      [IDL.Vec(AirdropAssignment)],
      [IDL.Record({ 'failed' : IDL.Nat, 'succeeded' : IDL.Nat })],
      [],
    ),
  'batchAssignPoolNFTs' : IDL.Func(
      [IDL.Vec(IDL.Nat), AssignAction],
      [IDL.Nat],
      [],
    ),
  'batchAssignToQR' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [IDL.Vec(QRAssignmentResult)],
      [],
    ),
  'batchListOnShop' : IDL.Func(
      [IDL.Vec(ShopAssignment)],
      [IDL.Record({ 'failed' : IDL.Nat, 'succeeded' : IDL.Nat })],
      [],
    ),
  'batchMintFoundersCollection' : IDL.Func(
      [IDL.Vec(FoundersMintInput)],
      [IDL.Vec(FoundersMintResult)],
      [],
    ),
  'beginArtworkUpload' : IDL.Func([IDL.Nat], [], []),
  'bulkCreateProducts' : IDL.Func(
      [IDL.Vec(CreateProductInput)],
      [IDL.Vec(BulkCreateResult)],
      [],
    ),
  'buyResaleListing' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'cancelOffer' : IDL.Func([IDL.Text], [Offer], []),
  'cancelResaleListing' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'clearArtworkFiles' : IDL.Func([], [], []),
  'counterOffer' : IDL.Func([CounterOfferInput], [Offer], []),
  'createBatchGiftPack' : IDL.Func(
      [IDL.Vec(PlantId)],
      [IDL.Variant({ 'ok' : BatchGiftPackPublic, 'err' : IDL.Text })],
      [],
    ),
  'createComment' : IDL.Func([CreateCommentInput], [CommentPublic], []),
  'createDAOProposal' : IDL.Func([CreateProposalInput], [ProposalPublic], []),
  'createOrder' : IDL.Func(
      [IDL.Principal, CreateOrderInput],
      [OrderPublic],
      [],
    ),
  'createPlant' : IDL.Func([CreatePlantInput], [PlantPublic], []),
  'createPost' : IDL.Func([CreatePostInput], [PostPublic], []),
  'createProduct' : IDL.Func([CreateProductInput], [ProductPublic], []),
  'createRecipe' : IDL.Func([CreateRecipeInput], [Recipe], []),
  'createTray' : IDL.Func([CreateTrayInput], [TrayPublic], []),
  'dabTransform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'deletePost' : IDL.Func([PostId], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'deleteRecipe' : IDL.Func([RecipeId], [IDL.Bool], []),
  'deleteTray' : IDL.Func([TrayId], [], []),
  'editPost' : IDL.Func([PostId, IDL.Text], [PostPublic], []),
  'ensureAdminProfile' : IDL.Func([], [], []),
  'ensureCallerProfile' : IDL.Func([], [], []),
  'finalizeArtworkUpload' : IDL.Func([], [UploadResult], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'generateAllPoolNFTs' : IDL.Func([], [IDL.Nat], []),
  'generateClaimToken' : IDL.Func(
      [PlantId, RarityTier],
      [ClaimTokenPublic],
      [],
    ),
  'generatePickupQRPayload' : IDL.Func([PlantId], [IDL.Text], ['query']),
  'getActiveResaleListings' : IDL.Func(
      [],
      [IDL.Vec(ResaleListingPublic)],
      ['query'],
    ),
  'getAdminPrincipal' : IDL.Func([], [IDL.Text], ['query']),
  'getAdminPrincipals' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getArtworkFile' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Vec(IDL.Nat8))], []),
  'getArtworkUploadResult' : IDL.Func([], [UploadResult], ['query']),
  'getArtworkUploadStatus' : IDL.Func([], [UploadSessionStatus], ['query']),
  'getBatchGiftPack' : IDL.Func(
      [ClaimTokenId],
      [IDL.Opt(BatchGiftPackPublic)],
      ['query'],
    ),
  'getCallerMembership' : IDL.Func(
      [],
      [IDL.Opt(MembershipNFTPublic)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCanisterId' : IDL.Func([], [IDL.Text], ['query']),
  'getClaimToken' : IDL.Func(
      [ClaimTokenId],
      [IDL.Opt(ClaimTokenPublic)],
      ['query'],
    ),
  'getDAOProposal' : IDL.Func(
      [ProposalId],
      [IDL.Opt(ProposalPublic)],
      ['query'],
    ),
  'getDAOStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalVotes' : IDL.Nat,
          'totalProposals' : IDL.Nat,
          'activeProposals' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getFollowersCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getFollowingCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getForSalePlants' : IDL.Func([], [IDL.Vec(PlantPublic)], ['query']),
  'getMembershipPriceInToken' : IDL.Func([OracleToken], [IDL.Nat], ['query']),
  'getMyOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
  'getMyResaleListings' : IDL.Func(
      [],
      [IDL.Vec(ResaleListingPublic)],
      ['query'],
    ),
  'getMySchedules' : IDL.Func([], [IDL.Vec(SavedSchedule)], []),
  'getMyWeatherRecords' : IDL.Func([IDL.Nat], [IDL.Vec(WeatherRecord)], []),
  'getOffer' : IDL.Func([IDL.Text], [IDL.Opt(Offer)], ['query']),
  'getOffersForNft' : IDL.Func([IDL.Text], [IDL.Vec(Offer)], ['query']),
  'getOffersReceived' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(OrderPublic)], ['query']),
  'getPlant' : IDL.Func([PlantId], [IDL.Opt(PlantPublic)], ['query']),
  'getPlantTimeline' : IDL.Func([PlantId], [IDL.Opt(PlantTimeline)], ['query']),
  'getPoolDashboard' : IDL.Func([], [PoolDashboard], []),
  'getPoolNFT' : IDL.Func([IDL.Nat], [IDL.Opt(PoolNFTPublic)], ['query']),
  'getPoolNFTs' : IDL.Func(
      [IDL.Opt(PoolNFTStatus__1), IDL.Nat, IDL.Nat],
      [IDL.Vec(PoolNFTPublic__1)],
      ['query'],
    ),
  'getPoolStats' : IDL.Func([], [PoolStats], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(ProductPublic)], ['query']),
  'getPublicProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getRecipe' : IDL.Func([RecipeId], [IDL.Opt(Recipe)], ['query']),
  'getScheduleByShareToken' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SavedSchedule)],
      ['query'],
    ),
  'getScheduleData' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Vec(ScheduleEntry)],
      ['query'],
    ),
  'getTokenPriceInIcp' : IDL.Func([OracleToken], [IDL.Nat], ['query']),
  'getTokenPrices' : IDL.Func([], [IDL.Vec(TokenPrice)], ['query']),
  'getTray' : IDL.Func([TrayId], [IDL.Opt(TrayPublic)], ['query']),
  'getTreasuryBalance' : IDL.Func([TreasuryToken], [IDL.Nat], ['query']),
  'getTreasuryBalances' : IDL.Func([], [IDL.Vec(TreasuryBalance)], ['query']),
  'getTreasuryLedger' : IDL.Func([], [IDL.Vec(TreasuryTransaction)], ['query']),
  'getUpgradeHistory' : IDL.Func(
      [PlantId],
      [IDL.Vec(LifecycleUpgradeEvent)],
      ['query'],
    ),
  'getUserPosts' : IDL.Func([IDL.Principal], [IDL.Vec(PostPublic)], ['query']),
  'getWalletAddress' : IDL.Func([], [IDL.Text], ['query']),
  'getWalletBalances' : IDL.Func([], [IDL.Vec(WalletToken)], []),
  'getWalletTransactions' : IDL.Func(
      [],
      [IDL.Vec(WalletTransaction)],
      ['query'],
    ),
  'hasDAOAccess' : IDL.Func([], [IDL.Bool], ['query']),
  'hasMembership' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'issueMembership' : IDL.Func(
      [
        IDL.Principal,
        MembershipTier,
        IDL.Variant({
          'EXT' : IDL.Null,
          'Hedera' : IDL.Null,
          'ICRC37' : IDL.Null,
        }),
      ],
      [MembershipNFTPublic],
      [],
    ),
  'likePost' : IDL.Func([PostId], [IDL.Nat], []),
  'listArtworkFiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'listArtworkLayers' : IDL.Func([], [IDL.Vec(ArtworkLayer)], []),
  'listCommentsByPost' : IDL.Func(
      [PostId],
      [IDL.Vec(CommentPublic)],
      ['query'],
    ),
  'listDAOProposals' : IDL.Func([], [IDL.Vec(ProposalPublic)], ['query']),
  'listMyPlants' : IDL.Func([], [IDL.Vec(PlantPublic)], []),
  'listNFTForResale' : IDL.Func(
      [PlantId, IDL.Float64],
      [IDL.Variant({ 'ok' : ResaleListingPublic, 'err' : IDL.Text })],
      [],
    ),
  'listOrdersByBuyer' : IDL.Func([], [IDL.Vec(OrderPublic)], ['query']),
  'listPlants' : IDL.Func([], [IDL.Vec(PlantPublic)], ['query']),
  'listPlantsByStage' : IDL.Func(
      [PlantStage],
      [IDL.Vec(PlantPublic)],
      ['query'],
    ),
  'listPoolNFTs' : IDL.Func(
      [IDL.Opt(PoolNFTStatus), IDL.Nat],
      [IDL.Vec(PoolNFTPublic)],
      [],
    ),
  'listPosts' : IDL.Func([], [IDL.Vec(PostPublic)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(ProductPublic)], ['query']),
  'listProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(ProductPublic)],
      ['query'],
    ),
  'listRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
  'listTrays' : IDL.Func([], [IDL.Vec(TrayPublic)], ['query']),
  'markPlantGerminated' : IDL.Func([PlantId, Timestamp], [], []),
  'mintEXT' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      [IDL.Text],
      [],
    ),
  'mintHederaNFT' : IDL.Func(
      [PlantId, IDL.Opt(IDL.Text), IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      [IDL.Text],
      [],
    ),
  'mintICRC37' : IDL.Func(
      [PlantId, IDL.Opt(IDL.Text), IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      [IDL.Text],
      [],
    ),
  'mintRWAProvenance' : IDL.Func([MintRWAProvenanceInput], [IDL.Text], []),
  'placeOrder' : IDL.Func([CreateOrderInput], [OrderPublic], []),
  'preGenerateNFTPool' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Nat)],
      [IDL.Record({ 'ok' : IDL.Bool, 'total' : IDL.Nat })],
      [],
    ),
  'priceOracleTransform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'redeemBatchClaim' : IDL.Func(
      [ClaimTokenId],
      [IDL.Variant({ 'ok' : BatchGiftPackPublic, 'err' : IDL.Text })],
      [],
    ),
  'redeemClaim' : IDL.Func([ClaimTokenId], [ClaimTokenPublic], []),
  'refreshTokenPrices' : IDL.Func([], [IDL.Bool], []),
  'rejectOffer' : IDL.Func([IDL.Text], [Offer], []),
  'removePlantPhoto' : IDL.Func([PlantId, IDL.Text], [], []),
  'resetOrphanPoolNFT' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'resetPoolNFT' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([SaveProfileInput], [], []),
  'saveSchedule' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [ScheduleId], []),
  'seedDefaultRecipes' : IDL.Func([], [], []),
  'sendToken' : IDL.Func(
      [SendTokenInput],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'setForSale' : IDL.Func([PlantId, IDL.Bool], [], []),
  'setPlantNFT' : IDL.Func([PlantId, IDL.Text], [], []),
  'storeArtworkFile' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Nat8), IDL.Text],
      [StoredFile],
      [],
    ),
  'submitOffer' : IDL.Func([SubmitOfferInput], [Offer], []),
  'toggleCooked' : IDL.Func([PlantId], [], []),
  'toggleRecipeFeatured' : IDL.Func([RecipeId], [IDL.Opt(Recipe)], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transplantCell' : IDL.Func([TransplantInput], [PlantPublic], []),
  'treasuryDeposit' : IDL.Func(
      [TreasuryToken, IDL.Nat, IDL.Opt(IDL.Text)],
      [TreasuryTransaction],
      [],
    ),
  'treasuryTransfer' : IDL.Func(
      [TreasuryToken, IDL.Nat, IDL.Principal, IDL.Principal, IDL.Opt(IDL.Text)],
      [TreasuryTransaction],
      [],
    ),
  'treasuryWithdraw' : IDL.Func(
      [TreasuryToken, IDL.Nat, IDL.Principal, IDL.Opt(IDL.Text)],
      [TreasuryTransaction],
      [],
    ),
  'triggerLifecycleUpgrade' : IDL.Func([PlantId, IDL.Text], [IDL.Text], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'unlikePost' : IDL.Func([PostId], [IDL.Nat], []),
  'updateCellData' : IDL.Func([UpdateCellDataInput], [], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updatePlantMetadata' : IDL.Func([UpdatePlantMetadataInput], [], []),
  'updatePlantStage' : IDL.Func([PlantId, PlantStage, IDL.Text], [], []),
  'updateProduct' : IDL.Func([UpdateProductInput], [], []),
  'updateRecipe' : IDL.Func([UpdateRecipeInput], [IDL.Opt(Recipe)], []),
  'updateTrayName' : IDL.Func([TrayId, IDL.Text], [], []),
  'uploadArtworkChunk' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Vec(IDL.Nat8)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'voteOnProposal' : IDL.Func([ProposalId, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OfferStatus = IDL.Variant({
    'Countered' : IDL.Null,
    'Rejected' : IDL.Null,
    'Accepted' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const OfferToken = IDL.Variant({
    'ICP' : IDL.Null,
    'ckBTC' : IDL.Null,
    'ckETH' : IDL.Null,
    'ckUSDC' : IDL.Null,
    'ckUSDT' : IDL.Null,
  });
  const OfferAction = IDL.Variant({
    'Countered' : IDL.Null,
    'Rejected' : IDL.Null,
    'Accepted' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Submitted' : IDL.Null,
  });
  const OfferHistoryEntry = IDL.Record({
    'by' : IDL.Principal,
    'token' : OfferToken,
    'action' : OfferAction,
    'timestamp' : Timestamp,
    'amount' : IDL.Nat,
  });
  const Offer = IDL.Record({
    'id' : IDL.Text,
    'nft_id' : IDL.Text,
    'status' : OfferStatus,
    'updated_at' : Timestamp,
    'history' : IDL.Vec(OfferHistoryEntry),
    'created_at' : Timestamp,
    'seller' : IDL.Principal,
    'offered_token' : OfferToken,
    'offered_amount' : IDL.Nat,
    'buyer' : IDL.Principal,
    'icp_equivalent' : IDL.Nat,
  });
  const ArtworkLayerId = IDL.Nat;
  const ArtworkLayer = IDL.Record({
    'id' : ArtworkLayerId,
    'layer_number' : IDL.Nat,
    'name' : IDL.Text,
    'object_key' : IDL.Text,
    'uploaded_at' : Timestamp,
  });
  const PlantId = IDL.Nat;
  const AddFeedingInput = IDL.Record({
    'dosage_amount' : IDL.Text,
    'date' : Timestamp,
    'nutrient_type' : IDL.Text,
    'product_name' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'plant_id' : PlantId,
  });
  const FeedingId = IDL.Nat;
  const FeedingPublic = IDL.Record({
    'id' : FeedingId,
    'dosage_amount' : IDL.Text,
    'date' : Timestamp,
    'nutrient_type' : IDL.Text,
    'product_name' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'plant_id' : PlantId,
  });
  const AddWeatherRecordInput = IDL.Record({
    'latitude' : IDL.Float64,
    'temperature_max' : IDL.Float64,
    'temperature_min' : IDL.Float64,
    'precipitation' : IDL.Float64,
    'wind_speed' : IDL.Opt(IDL.Float64),
    'date' : IDL.Text,
    'humidity' : IDL.Opt(IDL.Float64),
    'longitude' : IDL.Float64,
  });
  const WeatherRecordId = IDL.Nat;
  const WeatherRecord = IDL.Record({
    'id' : WeatherRecordId,
    'latitude' : IDL.Float64,
    'temperature_max' : IDL.Float64,
    'temperature_min' : IDL.Float64,
    'precipitation' : IDL.Float64,
    'wind_speed' : IDL.Opt(IDL.Float64),
    'date' : IDL.Text,
    'user' : IDL.Principal,
    'humidity' : IDL.Opt(IDL.Float64),
    'recorded_at' : Timestamp,
    'longitude' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AssignAction = IDL.Variant({
    'AssignToQR' : IDL.Record({ 'claim_token' : IDL.Text }),
    'ListOnShop' : IDL.Record({ 'product_id' : IDL.Nat }),
    'Airdrop' : IDL.Record({ 'to' : IDL.Principal }),
  });
  const AirdropAssignment = IDL.Record({
    'recipient' : IDL.Principal,
    'nftId' : IDL.Nat,
  });
  const QRAssignmentResult = IDL.Record({
    'claimTokenId' : IDL.Text,
    'nftId' : IDL.Nat,
  });
  const ShopAssignment = IDL.Record({ 'nftId' : IDL.Nat, 'price' : IDL.Nat });
  const RarityTier = IDL.Variant({
    'Rare' : IDL.Null,
    'Uncommon' : IDL.Null,
    'Common' : IDL.Null,
  });
  const NFTStandard = IDL.Variant({
    'EXT' : IDL.Null,
    'Hedera' : IDL.Null,
    'ICRC37' : IDL.Null,
  });
  const FoundersMintInput = IDL.Record({
    'layerCombination' : IDL.Vec(IDL.Nat),
    'recipient' : IDL.Principal,
    'rarityTier' : RarityTier,
    'badgeImageKey' : IDL.Text,
    'nft_standard' : NFTStandard,
    'compositeImageKey' : IDL.Text,
  });
  const FoundersMintResult = IDL.Record({
    'tokenId' : IDL.Text,
    'recipient' : IDL.Principal,
    'standard' : NFTStandard,
  });
  const InventoryCategory = IDL.Variant({
    'OtherSize' : IDL.Text,
    'Gal1' : IDL.Null,
    'Gal3' : IDL.Null,
    'Gal5' : IDL.Null,
    'Oz16' : IDL.Null,
    'InGround' : IDL.Null,
  });
  const ProductCategory = IDL.Variant({
    'Spice' : IDL.Null,
    'Seedling' : IDL.Null,
    'GardenInputs' : IDL.Null,
    'Gallon1' : IDL.Null,
    'Gallon5' : IDL.Null,
  });
  const CreateProductInput = IDL.Record({
    'image_key' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'price_cents' : IDL.Nat,
    'description' : IDL.Text,
    'inventory_category' : IDL.Opt(InventoryCategory),
    'image_keys' : IDL.Vec(IDL.Text),
    'category' : ProductCategory,
    'variety' : IDL.Opt(IDL.Text),
    'plant_id' : IDL.Opt(PlantId),
  });
  const ProductId = IDL.Nat;
  const ProductPublic = IDL.Record({
    'id' : ProductId,
    'active' : IDL.Bool,
    'image_key' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'price_cents' : IDL.Nat,
    'description' : IDL.Text,
    'inventory_category' : IDL.Opt(InventoryCategory),
    'image_keys' : IDL.Vec(IDL.Text),
    'category' : ProductCategory,
    'variety' : IDL.Opt(IDL.Text),
    'plant_id' : IDL.Opt(PlantId),
  });
  const BulkCreateResult = IDL.Variant({
    'ok' : ProductPublic,
    'err' : IDL.Text,
  });
  const CounterOfferInput = IDL.Record({
    'counter_amount' : IDL.Nat,
    'offer_id' : IDL.Text,
    'counter_token' : OfferToken,
  });
  const ClaimTokenId = IDL.Text;
  const BatchGiftPackPublic = IDL.Record({
    'id' : IDL.Text,
    'creator' : IDL.Principal,
    'plant_ids' : IDL.Vec(PlantId),
    'redeemed' : IDL.Bool,
    'created_at' : Timestamp,
    'redeemed_by' : IDL.Opt(IDL.Principal),
    'claim_token_id' : ClaimTokenId,
    'highest_rarity_pct' : IDL.Nat,
  });
  const PostId = IDL.Nat;
  const CreateCommentInput = IDL.Record({
    'post_id' : PostId,
    'content' : IDL.Text,
  });
  const CommentId = IDL.Nat;
  const CommentPublic = IDL.Record({
    'id' : CommentId,
    'post_id' : PostId,
    'content' : IDL.Text,
    'created_at' : Timestamp,
    'author' : IDL.Principal,
    'author_username' : IDL.Opt(IDL.Text),
  });
  const ProposalType = IDL.Variant({
    'General' : IDL.Null,
    'Seasoning' : IDL.Null,
    'PlantVariety' : IDL.Null,
  });
  const CreateProposalInput = IDL.Record({
    'title' : IDL.Text,
    'ends_at' : Timestamp,
    'description' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
    'proposal_type' : ProposalType,
  });
  const ProposalId = IDL.Nat;
  const ProposalPublic = IDL.Record({
    'id' : ProposalId,
    'title' : IDL.Text,
    'vote_counts' : IDL.Vec(IDL.Nat),
    'ends_at' : Timestamp,
    'description' : IDL.Text,
    'created_at' : Timestamp,
    'created_by' : IDL.Principal,
    'voter_count' : IDL.Nat,
    'caller_vote' : IDL.Opt(IDL.Nat),
    'options' : IDL.Vec(IDL.Text),
    'proposal_type' : ProposalType,
  });
  const OrderItem = IDL.Record({
    'product_id' : ProductId,
    'price_cents' : IDL.Nat,
    'quantity' : IDL.Nat,
    'plant_id' : IDL.Opt(PlantId),
  });
  const CreateOrderInput = IDL.Record({
    'shipping_address' : IDL.Opt(IDL.Text),
    'pickup' : IDL.Bool,
    'items' : IDL.Vec(OrderItem),
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'PickedUp' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Shipped' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const OrderPublic = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'shipping_address' : IDL.Opt(IDL.Text),
    'created_at' : Timestamp,
    'pickup' : IDL.Bool,
    'buyer' : IDL.Principal,
    'items' : IDL.Vec(OrderItem),
    'total_cents' : IDL.Nat,
  });
  const ContainerSize = IDL.Variant({
    'Gal5Bucket' : IDL.Null,
    'Gal1' : IDL.Null,
    'Gal3' : IDL.Null,
    'Gal5' : IDL.Null,
    'Oz16' : IDL.Null,
    'Gal7GrowBag' : IDL.Null,
    'Cell72' : IDL.Null,
    'Pot4Inch' : IDL.Null,
    'InGround' : IDL.Null,
    'Pot6Inch' : IDL.Null,
    'Gal10GrowBag' : IDL.Null,
    'Gal1New' : IDL.Null,
    'Gal3New' : IDL.Null,
    'Gal7Pot' : IDL.Null,
    'Cell128' : IDL.Null,
    'Gal15GrowBag' : IDL.Null,
    'Gal5GrowBag' : IDL.Null,
    'Other' : IDL.Text,
  });
  const TrayId = IDL.Nat;
  const CreatePlantInput = IDL.Record({
    'container_size' : IDL.Opt(ContainerSize),
    'date_purchased' : IDL.Opt(Timestamp),
    'origin' : IDL.Opt(IDL.Text),
    'common_name' : IDL.Opt(IDL.Text),
    'source_plant_id' : IDL.Opt(PlantId),
    'cell_position' : IDL.Nat,
    'watering_schedule' : IDL.Opt(IDL.Text),
    'pest_notes' : IDL.Opt(IDL.Text),
    'tray_id' : TrayId,
    'notes' : IDL.Text,
    'planting_date' : Timestamp,
    'additional_notes' : IDL.Opt(IDL.Text),
    'genetics' : IDL.Text,
    'variety' : IDL.Text,
    'nft_standard' : NFTStandard,
    'latin_name' : IDL.Opt(IDL.Text),
  });
  const PlantStage = IDL.Variant({
    'Seedling' : IDL.Null,
    'Seed' : IDL.Null,
    'Mature' : IDL.Null,
  });
  const PlantPublic = IDL.Record({
    'id' : PlantId,
    'nft_id' : IDL.Opt(IDL.Text),
    'container_size' : IDL.Opt(ContainerSize),
    'origin' : IDL.Opt(IDL.Text),
    'sold' : IDL.Bool,
    'is_transplanted' : IDL.Bool,
    'common_name' : IDL.Opt(IDL.Text),
    'for_sale' : IDL.Bool,
    'created_by' : IDL.Principal,
    'is_cooked' : IDL.Bool,
    'source_plant_id' : IDL.Opt(PlantId),
    'cell_position' : IDL.Nat,
    'watering_schedule' : IDL.Opt(IDL.Text),
    'pest_notes' : IDL.Opt(IDL.Text),
    'sold_to' : IDL.Opt(IDL.Principal),
    'stage' : PlantStage,
    'germination_date' : IDL.Opt(Timestamp),
    'tray_id' : TrayId,
    'notes' : IDL.Text,
    'planting_date' : Timestamp,
    'transplant_date' : IDL.Opt(Timestamp),
    'additional_notes' : IDL.Opt(IDL.Text),
    'photo_keys' : IDL.Vec(IDL.Text),
    'genetics' : IDL.Text,
    'variety' : IDL.Text,
    'transplant_plant_id' : IDL.Opt(PlantId),
    'nft_standard' : NFTStandard,
    'photos' : IDL.Vec(IDL.Text),
    'latin_name' : IDL.Opt(IDL.Text),
  });
  const CreatePostInput = IDL.Record({
    'content' : IDL.Text,
    'image_key' : IDL.Opt(IDL.Text),
    'anonymous' : IDL.Bool,
  });
  const PostPublic = IDL.Record({
    'id' : PostId,
    'updated_at' : Timestamp,
    'content' : IDL.Text,
    'author_text' : IDL.Text,
    'comment_count' : IDL.Nat,
    'image_key' : IDL.Opt(IDL.Text),
    'like_count' : IDL.Nat,
    'created_at' : Timestamp,
    'author_principal' : IDL.Opt(IDL.Principal),
    'author_username' : IDL.Opt(IDL.Text),
    'is_anonymous' : IDL.Bool,
    'caller_liked' : IDL.Bool,
  });
  const CreateRecipeInput = IDL.Record({
    'photo_key' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'instructions' : IDL.Vec(IDL.Text),
    'is_featured' : IDL.Bool,
    'shop_link' : IDL.Opt(IDL.Text),
    'shop_link_label' : IDL.Opt(IDL.Text),
    'application_notes' : IDL.Text,
    'full_name' : IDL.Text,
    'ingredients' : IDL.Vec(IDL.Text),
  });
  const RecipeId = IDL.Nat;
  const Recipe = IDL.Record({
    'id' : RecipeId,
    'updated_at' : Timestamp,
    'photo_key' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'created_at' : Timestamp,
    'instructions' : IDL.Vec(IDL.Text),
    'is_featured' : IDL.Bool,
    'shop_link' : IDL.Opt(IDL.Text),
    'shop_link_label' : IDL.Opt(IDL.Text),
    'application_notes' : IDL.Text,
    'full_name' : IDL.Text,
    'ingredients' : IDL.Vec(IDL.Text),
  });
  const CreateTrayInput = IDL.Record({
    'name' : IDL.Text,
    'planting_date' : Timestamp,
    'nft_standard' : NFTStandard,
  });
  const TrayPublic = IDL.Record({
    'id' : TrayId,
    'cells' : IDL.Vec(IDL.Opt(PlantId)),
    'name' : IDL.Text,
    'cell_count' : IDL.Nat,
    'planting_date' : Timestamp,
    'nft_standard' : NFTStandard,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const LayerSummary = IDL.Record({
    'file_names' : IDL.Vec(IDL.Text),
    'layer' : IDL.Text,
    'file_count' : IDL.Nat,
  });
  const UploadResult = IDL.Record({
    'layers_detected' : IDL.Nat,
    'asset_canister_id' : IDL.Text,
    'total_files' : IDL.Nat,
    'layer_summaries' : IDL.Vec(LayerSummary),
  });
  const ClaimTokenPublic = IDL.Record({
    'id' : ClaimTokenId,
    'created_at' : Timestamp,
    'redeemed_at' : IDL.Opt(Timestamp),
    'redeemed_by' : IDL.Opt(IDL.Principal),
    'claim_data' : IDL.Text,
    'rarity_tier' : RarityTier,
    'plant_id' : PlantId,
  });
  const ResaleListingPublic = IDL.Record({
    'id' : IDL.Text,
    'seller' : IDL.Principal,
    'is_active' : IDL.Bool,
    'price_icp' : IDL.Float64,
    'rarity_tier' : RarityTier,
    'listed_at' : Timestamp,
    'plant_id' : PlantId,
  });
  const UploadSessionStatus = IDL.Record({
    'total_chunks' : IDL.Nat,
    'received' : IDL.Nat,
    'started_at' : Timestamp,
  });
  const MembershipTier = IDL.Variant({
    'Premium' : IDL.Null,
    'Standard' : IDL.Null,
  });
  const MembershipNFTPublic = IDL.Record({
    'id' : IDL.Nat,
    'nft_id' : IDL.Opt(IDL.Text),
    'issued_at' : Timestamp,
    'owner' : IDL.Principal,
    'tier' : MembershipTier,
    'is_founder' : IDL.Bool,
    'layer_combination' : IDL.Vec(IDL.Nat),
    'rarity_tier' : IDL.Opt(RarityTier),
    'nft_standard' : IDL.Variant({
      'EXT' : IDL.Null,
      'Hedera' : IDL.Null,
      'ICRC37' : IDL.Null,
    }),
  });
  const UserProfilePublic = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'avatar_key' : IDL.Opt(IDL.Text),
    'following_count' : IDL.Nat,
    'created_at' : Timestamp,
    'follower_count' : IDL.Nat,
    'principal_id' : IDL.Principal,
  });
  const OracleToken = IDL.Variant({
    'ICP' : IDL.Null,
    'ckBTC' : IDL.Null,
    'ckETH' : IDL.Null,
    'ckUSDC' : IDL.Null,
    'ckUSDT' : IDL.Null,
  });
  const ScheduleId = IDL.Text;
  const SavedSchedule = IDL.Record({
    'id' : ScheduleId,
    'owner' : IDL.Principal,
    'created_at' : Timestamp,
    'stage' : IDL.Text,
    'inputs' : IDL.Vec(IDL.Text),
    'share_token' : IDL.Text,
  });
  const StageHistory = IDL.Record({
    'stage' : PlantStage,
    'notes' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const PlantTimeline = IDL.Record({
    'stage_history' : IDL.Vec(StageHistory),
    'feedings' : IDL.Vec(FeedingPublic),
    'plant' : PlantPublic,
  });
  const PoolDashboard = IDL.Record({
    'total' : IDL.Nat,
    'listed_on_shop' : IDL.Nat,
    'assigned_to_qr' : IDL.Nat,
    'airdropped' : IDL.Nat,
    'ready' : IDL.Nat,
  });
  const PoolNFTStatus = IDL.Variant({
    'ListedOnShop' : IDL.Record({ 'at' : Timestamp, 'product_id' : IDL.Nat }),
    'Ready' : IDL.Null,
    'AssignedToQR' : IDL.Record({ 'at' : Timestamp, 'claim_token' : IDL.Text }),
    'Airdropped' : IDL.Record({ 'at' : Timestamp, 'to' : IDL.Principal }),
  });
  const PoolNFTRarity = IDL.Variant({
    'Rare' : IDL.Null,
    'Uncommon' : IDL.Null,
    'Common' : IDL.Null,
  });
  const PoolNFTPublic = IDL.Record({
    'id' : IDL.Nat,
    'status' : PoolNFTStatus,
    'generated_at' : Timestamp,
    'token_id' : IDL.Text,
    'image_key' : IDL.Text,
    'layer_combo' : IDL.Vec(IDL.Text),
    'rarity' : PoolNFTRarity,
  });
  const PoolNFTStatus__1 = IDL.Variant({
    'Shop' : IDL.Null,
    'QRAssigned' : IDL.Null,
    'Ready' : IDL.Null,
    'Airdropped' : IDL.Null,
  });
  const PoolNFTPublic__1 = IDL.Record({
    'id' : IDL.Nat,
    'status' : PoolNFTStatus__1,
    'shopProductId' : IDL.Opt(IDL.Nat),
    'assignedAt' : IDL.Opt(Timestamp),
    'assignedTo' : IDL.Opt(IDL.Principal),
    'layerCombination' : IDL.Vec(IDL.Nat),
    'rarityTier' : RarityTier,
    'claimTokenId' : IDL.Opt(IDL.Text),
    'compositeImageKey' : IDL.Text,
  });
  const PoolStats = IDL.Record({
    'shop' : IDL.Nat,
    'totalByRarity' : IDL.Record({
      'rare' : IDL.Nat,
      'common' : IDL.Nat,
      'uncommon' : IDL.Nat,
    }),
    'qrAssigned' : IDL.Nat,
    'airdropped' : IDL.Nat,
    'ready' : IDL.Nat,
  });
  const ScheduleEntry = IDL.Record({
    'timing' : IDL.Text,
    'dilution' : IDL.Text,
    'stage' : IDL.Text,
    'notes' : IDL.Text,
    'frequency' : IDL.Text,
    'input_name' : IDL.Text,
  });
  const TokenPrice = IDL.Record({
    'token' : OracleToken,
    'price_in_icp_e8s' : IDL.Nat,
    'last_updated' : Timestamp,
  });
  const TreasuryToken = IDL.Variant({
    'ICP' : IDL.Null,
    'ckBTC' : IDL.Null,
    'ckETH' : IDL.Null,
    'ckUSDC' : IDL.Null,
    'ckUSDT' : IDL.Null,
  });
  const TreasuryBalance = IDL.Record({
    'token' : TreasuryToken,
    'balance_e8s' : IDL.Nat,
  });
  const TreasuryTxType = IDL.Variant({
    'Deposit' : IDL.Null,
    'Withdrawal' : IDL.Null,
    'OfferSettlement' : IDL.Null,
    'Transfer' : IDL.Null,
  });
  const TreasuryTransaction = IDL.Record({
    'id' : IDL.Text,
    'token' : TreasuryToken,
    'to_principal' : IDL.Opt(IDL.Principal),
    'memo' : IDL.Opt(IDL.Text),
    'from_principal' : IDL.Opt(IDL.Principal),
    'amount_e8s' : IDL.Nat,
    'offer_id' : IDL.Opt(IDL.Text),
    'timestamp' : Timestamp,
    'tx_type' : TreasuryTxType,
  });
  const LifecycleUpgradeEvent = IDL.Record({
    'new_stage' : IDL.Text,
    'old_nft_id' : IDL.Opt(IDL.Text),
    'old_stage' : IDL.Text,
    'upgraded_at' : Timestamp,
    'new_nft_id' : IDL.Text,
    'plant_id' : PlantId,
  });
  const WalletToken = IDL.Record({
    'decimals' : IDL.Nat8,
    'balance' : IDL.Nat,
    'name' : IDL.Text,
    'usdValue' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const TxStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const TxType = IDL.Variant({ 'receive' : IDL.Null, 'send' : IDL.Null });
  const WalletTransaction = IDL.Record({
    'id' : IDL.Text,
    'status' : TxStatus,
    'counterparty' : IDL.Text,
    'tokenSymbol' : IDL.Text,
    'timestamp' : Timestamp,
    'txType' : TxType,
    'amount' : IDL.Nat,
  });
  const MintRWAProvenanceInput = IDL.Record({
    'custom_notes' : IDL.Text,
    'artwork_layer_id' : ArtworkLayerId,
    'rarity_tier' : IDL.Nat,
    'plant_id' : PlantId,
  });
  const SaveProfileInput = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'avatar_key' : IDL.Opt(IDL.Text),
  });
  const SendTokenInput = IDL.Record({
    'tokenSymbol' : IDL.Text,
    'recipientAddress' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const StoredFile = IDL.Record({
    'data' : IDL.Vec(IDL.Nat8),
    'path' : IDL.Text,
    'size' : IDL.Nat,
    'mime_type' : IDL.Text,
    'layer' : IDL.Text,
    'filename' : IDL.Text,
    'uploaded_at' : Timestamp,
  });
  const SubmitOfferInput = IDL.Record({
    'nft_id' : IDL.Text,
    'offered_token' : OfferToken,
    'offered_amount' : IDL.Nat,
  });
  const TransplantInput = IDL.Record({
    'container_size' : ContainerSize,
    'plant_id' : PlantId,
  });
  const UpdateCellDataInput = IDL.Record({
    'origin' : IDL.Opt(IDL.Text),
    'common_name' : IDL.Opt(IDL.Text),
    'watering_schedule' : IDL.Opt(IDL.Text),
    'pest_notes' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'additional_notes' : IDL.Opt(IDL.Text),
    'plant_id' : PlantId,
    'latin_name' : IDL.Opt(IDL.Text),
  });
  const UpdatePlantMetadataInput = IDL.Record({
    'notes' : IDL.Opt(IDL.Text),
    'genetics' : IDL.Opt(IDL.Text),
    'photos' : IDL.Opt(IDL.Vec(IDL.Text)),
    'plant_id' : PlantId,
  });
  const UpdateProductInput = IDL.Record({
    'active' : IDL.Opt(IDL.Bool),
    'product_id' : ProductId,
    'image_key' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'price_cents' : IDL.Opt(IDL.Nat),
    'description' : IDL.Opt(IDL.Text),
    'image_keys' : IDL.Opt(IDL.Vec(IDL.Text)),
  });
  const UpdateRecipeInput = IDL.Record({
    'id' : RecipeId,
    'photo_key' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
    'description' : IDL.Opt(IDL.Text),
    'instructions' : IDL.Opt(IDL.Vec(IDL.Text)),
    'is_featured' : IDL.Opt(IDL.Bool),
    'shop_link' : IDL.Opt(IDL.Text),
    'shop_link_label' : IDL.Opt(IDL.Text),
    'application_notes' : IDL.Opt(IDL.Text),
    'full_name' : IDL.Opt(IDL.Text),
    'ingredients' : IDL.Opt(IDL.Vec(IDL.Text)),
  });
  
  return IDL.Service({
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Nat8)],
        [],
      ),
    '_immutableObjectStorageGetCertificate' : IDL.Func(
        [],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'acceptOffer' : IDL.Func([IDL.Text], [Offer], []),
    'addArtworkLayer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [ArtworkLayer],
        [],
      ),
    'addFeedingRecord' : IDL.Func([AddFeedingInput], [FeedingPublic], []),
    'addPlantPhoto' : IDL.Func([PlantId, IDL.Text], [], []),
    'addWeatherRecord' : IDL.Func([AddWeatherRecordInput], [WeatherRecord], []),
    'adminSubmitToDAB' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'airdropNFT' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignPoolNFT' : IDL.Func([IDL.Nat, AssignAction], [], []),
    'batchAirdropFromPool' : IDL.Func(
        [IDL.Vec(AirdropAssignment)],
        [IDL.Record({ 'failed' : IDL.Nat, 'succeeded' : IDL.Nat })],
        [],
      ),
    'batchAssignPoolNFTs' : IDL.Func(
        [IDL.Vec(IDL.Nat), AssignAction],
        [IDL.Nat],
        [],
      ),
    'batchAssignToQR' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Vec(QRAssignmentResult)],
        [],
      ),
    'batchListOnShop' : IDL.Func(
        [IDL.Vec(ShopAssignment)],
        [IDL.Record({ 'failed' : IDL.Nat, 'succeeded' : IDL.Nat })],
        [],
      ),
    'batchMintFoundersCollection' : IDL.Func(
        [IDL.Vec(FoundersMintInput)],
        [IDL.Vec(FoundersMintResult)],
        [],
      ),
    'beginArtworkUpload' : IDL.Func([IDL.Nat], [], []),
    'bulkCreateProducts' : IDL.Func(
        [IDL.Vec(CreateProductInput)],
        [IDL.Vec(BulkCreateResult)],
        [],
      ),
    'buyResaleListing' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'cancelOffer' : IDL.Func([IDL.Text], [Offer], []),
    'cancelResaleListing' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'clearArtworkFiles' : IDL.Func([], [], []),
    'counterOffer' : IDL.Func([CounterOfferInput], [Offer], []),
    'createBatchGiftPack' : IDL.Func(
        [IDL.Vec(PlantId)],
        [IDL.Variant({ 'ok' : BatchGiftPackPublic, 'err' : IDL.Text })],
        [],
      ),
    'createComment' : IDL.Func([CreateCommentInput], [CommentPublic], []),
    'createDAOProposal' : IDL.Func([CreateProposalInput], [ProposalPublic], []),
    'createOrder' : IDL.Func(
        [IDL.Principal, CreateOrderInput],
        [OrderPublic],
        [],
      ),
    'createPlant' : IDL.Func([CreatePlantInput], [PlantPublic], []),
    'createPost' : IDL.Func([CreatePostInput], [PostPublic], []),
    'createProduct' : IDL.Func([CreateProductInput], [ProductPublic], []),
    'createRecipe' : IDL.Func([CreateRecipeInput], [Recipe], []),
    'createTray' : IDL.Func([CreateTrayInput], [TrayPublic], []),
    'dabTransform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'deletePost' : IDL.Func([PostId], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'deleteRecipe' : IDL.Func([RecipeId], [IDL.Bool], []),
    'deleteTray' : IDL.Func([TrayId], [], []),
    'editPost' : IDL.Func([PostId, IDL.Text], [PostPublic], []),
    'ensureAdminProfile' : IDL.Func([], [], []),
    'ensureCallerProfile' : IDL.Func([], [], []),
    'finalizeArtworkUpload' : IDL.Func([], [UploadResult], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'generateAllPoolNFTs' : IDL.Func([], [IDL.Nat], []),
    'generateClaimToken' : IDL.Func(
        [PlantId, RarityTier],
        [ClaimTokenPublic],
        [],
      ),
    'generatePickupQRPayload' : IDL.Func([PlantId], [IDL.Text], ['query']),
    'getActiveResaleListings' : IDL.Func(
        [],
        [IDL.Vec(ResaleListingPublic)],
        ['query'],
      ),
    'getAdminPrincipal' : IDL.Func([], [IDL.Text], ['query']),
    'getAdminPrincipals' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getArtworkFile' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Vec(IDL.Nat8))], []),
    'getArtworkUploadResult' : IDL.Func([], [UploadResult], ['query']),
    'getArtworkUploadStatus' : IDL.Func([], [UploadSessionStatus], ['query']),
    'getBatchGiftPack' : IDL.Func(
        [ClaimTokenId],
        [IDL.Opt(BatchGiftPackPublic)],
        ['query'],
      ),
    'getCallerMembership' : IDL.Func(
        [],
        [IDL.Opt(MembershipNFTPublic)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCanisterId' : IDL.Func([], [IDL.Text], ['query']),
    'getClaimToken' : IDL.Func(
        [ClaimTokenId],
        [IDL.Opt(ClaimTokenPublic)],
        ['query'],
      ),
    'getDAOProposal' : IDL.Func(
        [ProposalId],
        [IDL.Opt(ProposalPublic)],
        ['query'],
      ),
    'getDAOStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalVotes' : IDL.Nat,
            'totalProposals' : IDL.Nat,
            'activeProposals' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getFollowersCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getFollowingCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getForSalePlants' : IDL.Func([], [IDL.Vec(PlantPublic)], ['query']),
    'getMembershipPriceInToken' : IDL.Func([OracleToken], [IDL.Nat], ['query']),
    'getMyOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
    'getMyResaleListings' : IDL.Func(
        [],
        [IDL.Vec(ResaleListingPublic)],
        ['query'],
      ),
    'getMySchedules' : IDL.Func([], [IDL.Vec(SavedSchedule)], []),
    'getMyWeatherRecords' : IDL.Func([IDL.Nat], [IDL.Vec(WeatherRecord)], []),
    'getOffer' : IDL.Func([IDL.Text], [IDL.Opt(Offer)], ['query']),
    'getOffersForNft' : IDL.Func([IDL.Text], [IDL.Vec(Offer)], ['query']),
    'getOffersReceived' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(OrderPublic)], ['query']),
    'getPlant' : IDL.Func([PlantId], [IDL.Opt(PlantPublic)], ['query']),
    'getPlantTimeline' : IDL.Func(
        [PlantId],
        [IDL.Opt(PlantTimeline)],
        ['query'],
      ),
    'getPoolDashboard' : IDL.Func([], [PoolDashboard], []),
    'getPoolNFT' : IDL.Func([IDL.Nat], [IDL.Opt(PoolNFTPublic)], ['query']),
    'getPoolNFTs' : IDL.Func(
        [IDL.Opt(PoolNFTStatus__1), IDL.Nat, IDL.Nat],
        [IDL.Vec(PoolNFTPublic__1)],
        ['query'],
      ),
    'getPoolStats' : IDL.Func([], [PoolStats], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(ProductPublic)], ['query']),
    'getPublicProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getRecipe' : IDL.Func([RecipeId], [IDL.Opt(Recipe)], ['query']),
    'getScheduleByShareToken' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SavedSchedule)],
        ['query'],
      ),
    'getScheduleData' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Vec(ScheduleEntry)],
        ['query'],
      ),
    'getTokenPriceInIcp' : IDL.Func([OracleToken], [IDL.Nat], ['query']),
    'getTokenPrices' : IDL.Func([], [IDL.Vec(TokenPrice)], ['query']),
    'getTray' : IDL.Func([TrayId], [IDL.Opt(TrayPublic)], ['query']),
    'getTreasuryBalance' : IDL.Func([TreasuryToken], [IDL.Nat], ['query']),
    'getTreasuryBalances' : IDL.Func([], [IDL.Vec(TreasuryBalance)], ['query']),
    'getTreasuryLedger' : IDL.Func(
        [],
        [IDL.Vec(TreasuryTransaction)],
        ['query'],
      ),
    'getUpgradeHistory' : IDL.Func(
        [PlantId],
        [IDL.Vec(LifecycleUpgradeEvent)],
        ['query'],
      ),
    'getUserPosts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PostPublic)],
        ['query'],
      ),
    'getWalletAddress' : IDL.Func([], [IDL.Text], ['query']),
    'getWalletBalances' : IDL.Func([], [IDL.Vec(WalletToken)], []),
    'getWalletTransactions' : IDL.Func(
        [],
        [IDL.Vec(WalletTransaction)],
        ['query'],
      ),
    'hasDAOAccess' : IDL.Func([], [IDL.Bool], ['query']),
    'hasMembership' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'issueMembership' : IDL.Func(
        [
          IDL.Principal,
          MembershipTier,
          IDL.Variant({
            'EXT' : IDL.Null,
            'Hedera' : IDL.Null,
            'ICRC37' : IDL.Null,
          }),
        ],
        [MembershipNFTPublic],
        [],
      ),
    'likePost' : IDL.Func([PostId], [IDL.Nat], []),
    'listArtworkFiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'listArtworkLayers' : IDL.Func([], [IDL.Vec(ArtworkLayer)], []),
    'listCommentsByPost' : IDL.Func(
        [PostId],
        [IDL.Vec(CommentPublic)],
        ['query'],
      ),
    'listDAOProposals' : IDL.Func([], [IDL.Vec(ProposalPublic)], ['query']),
    'listMyPlants' : IDL.Func([], [IDL.Vec(PlantPublic)], []),
    'listNFTForResale' : IDL.Func(
        [PlantId, IDL.Float64],
        [IDL.Variant({ 'ok' : ResaleListingPublic, 'err' : IDL.Text })],
        [],
      ),
    'listOrdersByBuyer' : IDL.Func([], [IDL.Vec(OrderPublic)], ['query']),
    'listPlants' : IDL.Func([], [IDL.Vec(PlantPublic)], ['query']),
    'listPlantsByStage' : IDL.Func(
        [PlantStage],
        [IDL.Vec(PlantPublic)],
        ['query'],
      ),
    'listPoolNFTs' : IDL.Func(
        [IDL.Opt(PoolNFTStatus), IDL.Nat],
        [IDL.Vec(PoolNFTPublic)],
        [],
      ),
    'listPosts' : IDL.Func([], [IDL.Vec(PostPublic)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(ProductPublic)], ['query']),
    'listProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(ProductPublic)],
        ['query'],
      ),
    'listRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
    'listTrays' : IDL.Func([], [IDL.Vec(TrayPublic)], ['query']),
    'markPlantGerminated' : IDL.Func([PlantId, Timestamp], [], []),
    'mintEXT' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        [IDL.Text],
        [],
      ),
    'mintHederaNFT' : IDL.Func(
        [PlantId, IDL.Opt(IDL.Text), IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        [IDL.Text],
        [],
      ),
    'mintICRC37' : IDL.Func(
        [PlantId, IDL.Opt(IDL.Text), IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        [IDL.Text],
        [],
      ),
    'mintRWAProvenance' : IDL.Func([MintRWAProvenanceInput], [IDL.Text], []),
    'placeOrder' : IDL.Func([CreateOrderInput], [OrderPublic], []),
    'preGenerateNFTPool' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat)],
        [IDL.Record({ 'ok' : IDL.Bool, 'total' : IDL.Nat })],
        [],
      ),
    'priceOracleTransform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'redeemBatchClaim' : IDL.Func(
        [ClaimTokenId],
        [IDL.Variant({ 'ok' : BatchGiftPackPublic, 'err' : IDL.Text })],
        [],
      ),
    'redeemClaim' : IDL.Func([ClaimTokenId], [ClaimTokenPublic], []),
    'refreshTokenPrices' : IDL.Func([], [IDL.Bool], []),
    'rejectOffer' : IDL.Func([IDL.Text], [Offer], []),
    'removePlantPhoto' : IDL.Func([PlantId, IDL.Text], [], []),
    'resetOrphanPoolNFT' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'resetPoolNFT' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([SaveProfileInput], [], []),
    'saveSchedule' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [ScheduleId], []),
    'seedDefaultRecipes' : IDL.Func([], [], []),
    'sendToken' : IDL.Func(
        [SendTokenInput],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'setForSale' : IDL.Func([PlantId, IDL.Bool], [], []),
    'setPlantNFT' : IDL.Func([PlantId, IDL.Text], [], []),
    'storeArtworkFile' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat8), IDL.Text],
        [StoredFile],
        [],
      ),
    'submitOffer' : IDL.Func([SubmitOfferInput], [Offer], []),
    'toggleCooked' : IDL.Func([PlantId], [], []),
    'toggleRecipeFeatured' : IDL.Func([RecipeId], [IDL.Opt(Recipe)], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transplantCell' : IDL.Func([TransplantInput], [PlantPublic], []),
    'treasuryDeposit' : IDL.Func(
        [TreasuryToken, IDL.Nat, IDL.Opt(IDL.Text)],
        [TreasuryTransaction],
        [],
      ),
    'treasuryTransfer' : IDL.Func(
        [
          TreasuryToken,
          IDL.Nat,
          IDL.Principal,
          IDL.Principal,
          IDL.Opt(IDL.Text),
        ],
        [TreasuryTransaction],
        [],
      ),
    'treasuryWithdraw' : IDL.Func(
        [TreasuryToken, IDL.Nat, IDL.Principal, IDL.Opt(IDL.Text)],
        [TreasuryTransaction],
        [],
      ),
    'triggerLifecycleUpgrade' : IDL.Func([PlantId, IDL.Text], [IDL.Text], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'unlikePost' : IDL.Func([PostId], [IDL.Nat], []),
    'updateCellData' : IDL.Func([UpdateCellDataInput], [], []),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updatePlantMetadata' : IDL.Func([UpdatePlantMetadataInput], [], []),
    'updatePlantStage' : IDL.Func([PlantId, PlantStage, IDL.Text], [], []),
    'updateProduct' : IDL.Func([UpdateProductInput], [], []),
    'updateRecipe' : IDL.Func([UpdateRecipeInput], [IDL.Opt(Recipe)], []),
    'updateTrayName' : IDL.Func([TrayId, IDL.Text], [], []),
    'uploadArtworkChunk' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Vec(IDL.Nat8)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'voteOnProposal' : IDL.Func([ProposalId, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };